DOCNAME = user-manual

SVG_FIGURES       = 	../lib/figures/circle_menu_1.svg \
			../lib/figures/arc_menu.svg \
			../lib/figures/cityscape.svg
STATIC_FIGURES    =
GENERATED_FIGURES =

LIB_DIR = ../lib
include $(LIB_DIR)/Rules.make
