DOCNAME = architecture

SVG_FIGURES       = ../lib/figures/conceptual_overview.svg	\
		    ../lib/figures/arc_menu.svg			\
		    ../lib/figures/circle_menu_1.svg		\
		    ../lib/figures/cityscape.svg		\
		    figures/modules.svg
STATIC_FIGURES    =
GENERATED_FIGURES =

LIB_DIR = ../lib
include $(LIB_DIR)/Rules.make
