DOCNAME = presentation

SVG_FIGURES       =				\
	../lib/figures/rca-cartoon.svg		\
	../lib/figures/conceptual_overview.svg	\
	../lib/figures/fishstick.svg		\
	../lib/figures/ApplicationFactory-uml.svg \
	figures/interface.svg			\
	figures/Context-uml.svg			\
	figures/MediaCenter-uml.svg		\
	figures/Menu-uml.svg
STATIC_FIGURES    =
GENERATED_FIGURES =

LIB_DIR = ../lib
include $(LIB_DIR)/Rules.make
