#!/bin/bash

CONFIGDIR="`pwd`/data/"
DISP_CONFIG="file://${CONFIGDIR}java3d.conf"
LGCONFIG="file://${CONFIGDIR}lg3d.conf"
CLASSPATH="classes:lib/lg3d-core.jar:lib/j3d-contrib-utils.jar:lib/escher-0.2.2.lg.jar:${CLASSPATH}"
LD_LIBRARY_PATH="lib"
__GL_FSAA_MODE=2
RMI_PORT=44817
LG_DISPLAY=:1
LGX11HOME=lg3d-x11
XVFB_ARGS="$LG_DISPLAY -screen 0 640x480x24 +extension Composite +extension LGE -noreset"

export LD_LIBRARY_PATH CLASSPATH __GL_FSAA_MODE

# Start the X server
# FIXME - this should try to allocate a new DISPLAY rather than assuming :1
export DISPLAY=:1
XAUTHORITY="" $LGX11HOME/programs/Xserver/Xvfb $XVFB_ARGS &
sleep 2
xhost +
export DISPLAY=:0
xhost +

# Start the RMI registry, whatever that is
pkill -f "rmiregistry $RMI_PORT"
sleep 1
rmiregistry $RMI_PORT &

# Start the display server
# All these special JVM arguments are for tuning performance.  Without these,
# it's not possible to play video in real-time

# Bug fix for Ubuntu systems
LD_PRELOAD=/usr/lib/libGLU.so.1 java \
	-cp $CLASSPATH \
	\
	-server \
	-XX:PermSize=16m \
	-XX:MaxPermSize=24m \
	-XX:NewSize=128m \
	-XX:MaxNewSize=128m \
	-Xms256m -Xmx256m \
	-XX:+UseConcMarkSweepGC \
	-XX:+DisableExplicitGC \
	\
	-Dj3d.sortShape3DBounds="true" \
	-Dlg.etcdir=$CONFIGDIR \
	-Dlg.configurl=$LGCONFIG \
	-Dlg.displayconfigurl=$DISP_CONFIG \
	-Dlg.lgserverdisplay=$LG_DISPLAY \
	-Dlg.fws.mode=app \
	-Dlg.fws.x11.interfaceRequired=0.1 \
	\
	org.jdesktop.lg3d.apps.smrt.MediaCenter
