DOCNAME = design

SVG_FIGURES       = ../lib/figures/conceptual_overview.svg    \
		    ../lib/figures/MediaCenter-uml.svg        \
		    ../lib/figures/Context-uml.svg            \
		    ../lib/figures/Menu-uml.svg               \
		    ../lib/figures/Application-uml.svg        \
		    ../lib/figures/ApplicationFactory-uml.svg \
		    ../lib/figures/FilesystemCity-uml.svg     \
		    figures/modules.svg
STATIC_FIGURES    = figures/ring_menu.png figures/arc_menu.png figures/city_menu.png
GENERATED_FIGURES =

LIB_DIR = ../lib
include $(LIB_DIR)/Rules.make
