DOCNAME = presentation

SVG_FIGURES =							\
	../lib/figures/rca-cartoon.svg				\
	../lib/figures/conceptual_overview.svg			\
	../lib/figures/MediaCenter-uml.svg 			\
	../lib/figures/Menu-uml.svg 				\
	../lib/figures/Application-uml.svg 			\
	../lib/figures/ApplicationFactory-uml.svg		\
	../lib/figures/modular_overview.svg			\
	../lib/figures/fishstick.svg				\
	figures/example-session-01.svg				\
	figures/example-session-02.svg				\
	figures/example-session-03.svg				\
	figures/example-session-04.svg				\
	figures/example-session-05.svg				\
	figures/example-session-06.svg				\
	figures/example-session-07.svg				\
	figures/example-session-08.svg				\
	figures/example-session-09.svg				\
	figures/example-session-10.svg				\
	figures/example-session-11.svg				\
	../overview-presentation/figures/interface.svg		\
	../overview-presentation/figures/Context-uml.svg	\
	../overview-presentation/figures/MediaCenter-uml.svg	\
	../overview-presentation/figures/Menu-uml.svg		\
	../system-architecture/figures/modules.svg

PNG_FIGURES =				\
	../design/figures/ring_menu.png	\
	../design/figures/arc_menu.png	\
	../design/figures/city_menu.png

STATIC_FIGURES    =

GENERATED_FIGURES =

LIB_DIR = ../lib
include $(LIB_DIR)/Rules.make
